errors:
  - nergal@psu.ru
alerts:
  suppress:
    - on-found-puzzle
    - on-lost-puzzle
    - on-scope
  github:
    - nergal-perm
format:
  - short-title
  - title-length=100
tags:
  - pdd
  - task
